issue_95: Convert CounterOne.jsx to Function Component
codesydney/codesydneywebsite pull request #111
Opened 2023-03-30 05:30 UTC by soundarya-mv

Convert class component to function component
Moving static data to database.json

## Rationale

Convert class component to function component
Moving static data to database.json

## Advice for Reviewers & Testing Notes

Home page counter component needs to be tested.

## Screenshots:

- Add a screenshot or two of your changes, where applicable.

## Issue Resolved

*Note - This allows the issue to be automatically linked to the PR once the PR is submitted for review*
- Fixes #95

2023-03-30 07:24 UTC, davidtaing requested changes
Thanks for your PR @soundarya-mv, I've left four comments below. Please go through them when you get a chance.

I've marked two as `optional`, so you can either add additional changes or leave them as is. 

And I've marked another as a `nitpick`, due to it being a personal preference. No action required for the `nitpick` comments.

2023-03-30 07:24 UTC, davidtaing commented on public/database.json
> +    ]
**Nitpick:** 
For this I would have preferred for this to be done as a separate commit. In my opinion, we can group the changes as:
1. Migrate `CounterOne` component to functional component
2. Refactor `counterData` to `database.json` file

Minor and (probably a non-issue) since this is my personal opinion.

2023-03-30 07:24 UTC, davidtaing commented on src/elements/counters/CounterOne.jsx
> +import database from "../../../public/database.json";
**Optional:**
I just thought about this (and sorry for not raising this up in the earlier PRs). Perhaps we could destructure `counterData` here?

Feel free to leave this as it is or destructure. I'll leave that one up to you.

2023-03-30 07:24 UTC, davidtaing commented on src/elements/counters/CounterOne.jsx
>    }
Using `state` as the name for your state hook isn't great, because it doesn't offer any contextual information.

One of the questions that I like to ask myself is "Will I understand this in 6 months?"

So think about future you. Will you be able to understand what `state` does in 6 months?

2023-03-30 07:24 UTC, davidtaing commented on src/elements/counters/CounterOne.jsx
> +    <Fragment>
**Optional:**
If we go with the following syntax for Fragment, we can drop the import statement at the top of the file.

```JSX
<>
  // ...rest of component
</>
```

2023-04-03 02:53 UTC, soundarya-mv commented on src/elements/counters/CounterOne.jsx
>    }
Updated

2023-04-03 02:53 UTC, soundarya-mv commented on src/elements/counters/CounterOne.jsx
> +    <Fragment>
Change done

2023-04-03 02:55 UTC, soundarya-mv commented on src/elements/counters/CounterOne.jsx
> +import database from "../../../public/database.json";
@davidtaing  We have a folder named counter with 2 files as counterOne and counterTwo. I thought it was more structured when it is grouped that way. Please let me know, if we can remove the folder and have the 2 files in the elements folder directly.

2023-04-03 04:13 UTC, davidtaing commented on src/elements/counters/CounterOne.jsx
> +import database from "../../../public/database.json";
For context, this project was started from a paid React template. That's why we have multiple versions of the components in the codebase.

Personally, I've got no problems with moving to a more simplified structure (and even deleting the extra versions). But I'll defer the decision to our benevolent director. :smile: 

@engramar, what do you think? Should we keep the file structure untouched or go ahead and move the files into the `elements` folder?

2023-04-04 05:06 UTC, davidtaing commented on src/elements/counters/CounterOne.jsx
>    }
It's kinda my bad, but I should have mentioned that we don't need to use an object and instead directly use a boolean value.

Optional item for later. I'll merge this PR in for now.

Thanks for the good work.

2023-04-04 05:06 UTC, davidtaing approved these changes

2023-04-04 05:06 UTC, merged

2023-04-04 05:13 UTC, soundarya-mv commented on src/elements/counters/CounterOne.jsx
>    }
yes @davidtaing , even I thought of making that as a boolean data. But thought it was defined as an object intentionally for some reason expecting more data might be added to the object. So maintained it as the same.