fixed mispelled hamburger-menu css style issu
codesydney/codesydneywebsite pull request #44
Opened 2022-05-11 04:55 UTC by serhiicss

## Rationale

What does this pull request do?

## Advice for Reviewers & Testing Notes

- Explain how your change should be reviewed, and where reviewers should direct their attention.
- Explain (where relevant) how your change can be tested.

## Screenshots:

- Add a screenshot or two of your changes, where applicable.

## Issue Resolved

*Note - This allows the issue to be automatically linked to the PR once the PR is submitted for review*
- Fixes #<Issue Number>

2022-05-11 05:58 UTC, QjStout requested changes
Can you please fill out the submission template provided.
It's especially important to do the issue linking so that the issue you are resolving closes.

2022-05-11 05:58 UTC, QjStout commented on public/assets/scss/header/_header.scss
> +                        color: red !important;
What is this line for? (ln:276)

2022-05-11 06:00 UTC, QjStout commented on public/assets/scss/header/_header.scss
> +                        color: red !important;
BTW, it is fine to leave off the `Advice for Reviewers & Testing Notes` and `Screenshots` sections for simple stories, but if doing so please delete those sections before submitting

2022-05-12 02:23 UTC, serhiicss commented
I removed the extra line (I used it for testing and forgot to remove it initially). I mistakenly deleted the submission template and can't find it now :( sorry.

2022-05-12 08:13 UTC, QjStout commented
That's ok @serhiicss
Just write `closes #42` so that the issue is linked to your PR

2022-05-26 02:07 UTC, QjStout approved these changes
lgtm 👍

2022-05-26 02:07 UTC, merged